# Site settings
title: Jo Castilho
email: me@jocastilho.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Jo Castilho - Graphic Designer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jocastilho.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown